name: go-licenses

on:
  pull_request:
  push:
#    paths:
#  - "go.mod"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  licenses:
    runs-on: [ "ubuntu-latest" ]
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Check out OSS code into the Go module directory
        uses: actions/checkout@v3
        with:
          repository: willnorris/ts-oss
          path: oss

      - name: set up a bootstrap Go toolchain
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Install go-licenses
        run: |
          go install github.com/willnorris/go-licenses@tailscale

      - name: Run go-licenses
        id: licenses-win
        env:
          GOFLAGS: "-tags=cgo,windows"
        run: |
          go-licenses report ./... > oss/licenses.csv --template licenses.tmpl

      - uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06 # v1.6.0
        id: generate-token
        with:
          app_id: ${{ secrets.LICENSE_APP_ID }}
          private_key: ${{ secrets.LICENSE_APP_PRIVATE_KEY }}

      - name: Send pull request
        uses: peter-evans/create-pull-request@v4.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          path: oss
          author: License Bot <noreply@ts>
          branch: licenses/patch
          branch-suffix: short-commit-hash
          commit-message: "all: update third-party licenses"
          title: "all: update third-party licenses"
          body: Triggered by ${{ github.repository }}@${{ github.sha }}
          delete-branch: true
          assignees: willnorris
